name: backend-torchscript

on:
  push:
    paths:
      - "cmake"
      - "csrc"
      - ".github/workflows/backend-torchscript.yml"
      - "CMakeLists.txt"
      - "tools/scripts/build_ubuntu_x64_torchscript.py"

  pull_request:
    paths:
      - "cmake"
      - "csrc"
      - ".github/workflows/backend-torchscript.yml"
      - "CMakeLists.txt"
      - "tools/scripts/build_ubuntu_x64_torchscript.py"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_torchscript:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build mmdeploy with torchscript
        run: |
          python3 tools/scripts/build_ubuntu_x64_torchscript.py
          ls -lah build/lib/libmmdeploy_torchscript_ops.so
