name: backend-rknn

on:
  push:
    paths:
      - "cmake"
      - "csrc"
      - ".github/workflows/backend-rknn.yml"
      - "CMakeLists.txt"
      - "tools/scripts/ubuntu_cross_build_rknn.sh"

  pull_request:
    paths:
      - "cmake"
      - "csrc"
      - ".github/workflows/backend-rknn.yml"
      - "CMakeLists.txt"
      - "tools/scripts/ubuntu_cross_build_rknn.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_rknpu2:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: update
        run: sudo apt update
      - name: Cross build mmdeploy with rknpu2
        run: |
          sh -ex tools/scripts/ubuntu_cross_build_rknn.sh rk3588

  build_rknpu:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: update
        run: sudo apt update
      - name: Cross build mmdeploy with rknpu
        run: |
          sh -ex tools/scripts/ubuntu_cross_build_rknn.sh rv1126
