name: backend-ncnn

on:
  push:
    paths:
      - "cmake"
      - "csrc"
      - ".github/workflows/backend-ncnn.yml"
      - "CMakeLists.txt"
      - "tools/scripts/build_ubuntu_x64_ncnn.py"

  pull_request:
    paths:
      - "cmake"
      - "csrc"
      - ".github/workflows/backend-ncnn.yml"
      - "CMakeLists.txt"
      - "tools/scripts/build_ubuntu_x64_ncnn.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_ncnn:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build mmdeploy with ncnn
        run: |
          python3 tools/scripts/build_ubuntu_x64_ncnn.py
          python3 -c "import ncnn"
          ls -lah build/install/lib/libmmdeploy_ncnn_net.*
          ls -lah mmdeploy/lib/libmmdeploy_ncnn_ops.so
          ls -lah mmdeploy/backend/ncnn/mmdeploy_onnx2ncnn
          ls -lah mmdeploy/backend/ncnn/ncnn_ext.*.so
