name: backend-pplnn

on:
  push:
    paths: &paths
      - "cmake"
      - "csrc"
      - ".gitmodules"
      - ".github/workflows/backend-pplnn.yml"
      - "CMakeLists.txt"
      - "tools/scripts/build_ubuntu_x64_pplnn.py"

  pull_request:
    paths: *paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_pplnn:
    runs-on: ubuntu-18.04
    container:
      image: pytorch/pytorch:1.9.0-cuda11.1-cudnn8-devel
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: |
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
          apt update && apt install -y software-properties-common
          add-apt-repository ppa:git-core/ppa -y && apt-get update
          apt install -y gcc-multilib g++-multilib libpython${{matrix.python-version}}
          apt install -y wget git unzip
          apt-get clean
          rm -rf /var/lib/apt/lists/*
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build mmdeploy with pplnn
        run: |
          python3 tools/scripts/build_ubuntu_x64_pplnn.py
          python3 -c "import pyppl"
          ls -lah build/install
